config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new", as: :new
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
  validates :completed, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
    redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Tasks</h1>

<div class="flex">
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
<br>
  <p>
  <%= f.label :details %>
  <%= f.text_field :details %>
<br>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
</p>
  <p><%= @task.completed ? "This task is completed" : "This task is not completed" %></p>
<br>
  <%= f.submit %>
  <% end %>
<br>
</div>
<div>
  <%= link_to "Back to list", tasks_path %>
</div>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<body>
  <div>
    <ul class="check">
      <% @tasks.each do |task| %>
      <li>
        <%= check_box_tag(:completed, 1 , task.completed, disabled: true) %>
      <%= link_to task.title, task_path(task) %>
      </li>
      <% end %>
    </ul>
    <%= link_to "Add a new task", new_path %>
  </div>
</body>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<div class="flex">
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
<br>
  <%= f.label :details %>
  <%= f.text_field :details %>
<br>
  <%= f.submit %>
  <% end %>
<br>
</div>
<div>
  <%= link_to "Back to list", tasks_path %>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<div>
<p><%= @task.details %></p>
<p><%= check_box_tag(:completed, 1, @task.completed, disabled: true) %>
<%= @task.completed? ? "This task is completed" : "This task is not compeleted" %></p>
<p><%= link_to "Delete", destroy_path(@task), method: :delete, data: { confirm: "Are you sure?" } %></p>
</div>
<%= link_to "Back to list", tasks_path %>
<br>
<%= link_to "Go to edit", edit_path(@task) %>

app/views/tasks/task.html.erb
<h1>My tasks</h1>

<%= @ask %>

<h3>-You</h3>
<div class = answer>
<%= @answer %>
<h3>Your coach</h3>
</div>

<%= link_to "What else you want to ask?", _path %>